### ISSUE TITLE
`MVCSwagResponses` cannot define an array as result

### ISSUE THREAD

**Issue by danieleteti** [danieleteti/delphimvcframework#285]
Hi @joaoduarte19,
do you have a sample on how to generate the array schema definition using the  `MVCSwagResponses` attribute? Seeing the code I didn't found nothing (but I could be wrong).

What is needed is something like this:

```delphi

TCustomers = TObjectList<TCustomer>
end;

//...

    [MVCSwagSummary('Customers', 'Get a list of customer', 'getCustomers')]
    [MVCSwagResponses(200, 'Customers', TCustomers)]
    [MVCPath('/customers')]
    [MVCHTTPMethod([httpGET])]
    procedure GetCustomers;

```
With this code, the schema definition should include something similar to the following:

```yaml
type: array
items:
  type: object
  properties:
    id:
      type: integer
    //bla bla bla
```
